const {chromium}=require('playwright');const assert=require('node:assert/strict');const stub=require('./frontend-fixture.cjs');const fs=require('node:fs');const cp=require('node:child_process');
// A real two-second video/audio fixture exercises HTMLMediaElement, not a mocked player.
const media='/tmp/chronicles-player-test.webm';if(!fs.existsSync(media))cp.execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-f','lavfi','-i','testsrc=size=160x90:rate=15','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','2','-c:v','libvpx','-b:v','100k','-c:a','libopus','-y',media]);
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--autoplay-policy=no-user-gesture-required']});let checks=0;
for(const width of [320,390,1366,1920]){const p=await browser.newPage({viewport:{width,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'application/javascript',body:'('+stub.toString()+')()'}));await p.route('**/fixture-video.webm',r=>r.fulfill({contentType:'video/webm',body:fs.readFileSync(media)}));await p.goto(process.env.TEST_BASE_URL||'http://127.0.0.1:8009/');await p.waitForTimeout(200);
await p.evaluate(async()=>{auditSession={user:{id:'audit-user'},access_token:'fixture'};await hydrateProfileFromSession(auditSession,{render:false});renderProfile();closeAccountModal();window.playbackDelay=0;window.playbackFail=false;sb.functions.invoke=async()=>{await new Promise(r=>setTimeout(r,playbackDelay));return {data:playbackFail?{ok:false,message:'fixture failure'}:{ok:true,url:location.origin+'/fixture-video.webm'},error:null}};videoCache=[{id:'V-test',title:'Тестовый ролик',data:{conversion_status:'ready'}}];await openArchiveVideo('V-test')});
await p.waitForFunction(()=>!archiveMediaPlayer.paused&&archiveMediaPlayer.currentTime>.1);assert.equal(await p.locator('#archiveMediaLoop').isChecked(),true);checks++;
await p.evaluate(()=>showView('people'));await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>archiveMediaPlayer.paused),false);assert.equal(await p.locator('#archiveMediaDock').getAttribute('class'),'compact');checks++;
await p.locator('#archiveMediaToggle').click();const time=await p.evaluate(()=>archiveMediaPlayer.currentTime);await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>archiveMediaPlayer.currentTime),time);checks++;
await p.locator('#archiveMediaToggle').click();await p.evaluate(()=>archiveMediaPlayer.currentTime=1.8);await p.waitForTimeout(650);assert.equal(await p.evaluate(()=>archiveMediaPlayer.paused),false);assert.ok(await p.evaluate(()=>archiveMediaPlayer.currentTime<1.8));checks++;
await p.evaluate(()=>showView('chat'));await p.waitForTimeout(150);const layout=await p.evaluate(()=>({dock:archiveMediaDock.getBoundingClientRect().toJSON(),horizontal:document.documentElement.scrollWidth>innerWidth,composer:document.querySelector('#chat .composer')?.getBoundingClientRect().toJSON()}));assert.equal(layout.horizontal,false);assert.ok(layout.dock.right<=width+.1);if(layout.composer)assert.ok(layout.composer.bottom<=layout.dock.top,JSON.stringify(layout));checks++;
await p.locator('#archiveMediaLoop').uncheck();await p.evaluate(()=>archiveMediaPlayer.currentTime=1.8);await p.waitForFunction(()=>archiveMediaPlayer.ended);assert.equal(await p.locator('#archiveMediaToggle').textContent(),'Воспроизвести');checks++;
await p.locator('#archiveMediaStop').click();assert.equal(await p.locator('#archiveMediaDock').isVisible(),false);assert.equal(await p.evaluate(()=>archiveMediaPlayer.getAttribute('src')),null);checks++;
await p.evaluate(()=>{playbackDelay=300;void startArchiveMedia({id:'V-test',title:'Тестовый ролик',data:{conversion_status:'ready'}})});await p.evaluate(()=>stopArchiveMedia());await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>archiveMediaPlayer.getAttribute('src')),null);checks++;
await p.evaluate(async()=>{playbackDelay=0;playbackFail=true;await startArchiveMedia({id:'V-test',title:'Тестовый ролик',data:{conversion_status:'ready'}})});await p.locator('#archiveMediaRetry').waitFor();await p.evaluate(()=>playbackFail=false);await p.locator('#archiveMediaRetry').click();await p.waitForFunction(()=>!archiveMediaPlayer.paused);await p.evaluate(()=>clearPrivateSessionState());assert.equal(await p.locator('#archiveMediaDock').isVisible(),false);assert.equal(await p.evaluate(()=>archiveMediaPlayer.getAttribute('src')),null);checks++;
assert.deepEqual(errors,[]);await p.close()}
await browser.close();console.log(checks+' persistent archive player checks passed (real media, fixture Supabase).')})().catch(e=>{console.error(e);process.exit(1)});
