const stub=()=>{
 window.auditCalls=[];window.auditAuthError=null;window.auditVerifyError=null;window.auditImageUrl=null;window.auditDelay={};
 const people=[{id:'10A-11',number:11,group_name:'10А',canonical_name:'Ульянов Альберт',identification_status:'подтверждено',data:{}},{id:'10B-01',number:1,group_name:'10Б',canonical_name:'Другой участник',identification_status:'подтверждено',data:{}}];
 window.auditRows={profiles:[{id:'audit-user',display_name:'Альберт',role:'member',is_active:true,access_blocked:false,person_id:'10A-11',class_group:'10А'}],user_consents:[{user_id:'audit-user',accepted_at:'2026-10-08',withdrawn_at:null,consent_code:'archive_personal_data',consent_version:'2026-09-30-v3'}],archive_people:people,member_memories:[{user_id:'audit-user',school_dream:'Школьная мечта',life_now:'Жизнь сегодня',then_photo:null,now_photo:null,updated_at:'2026-10-08'}],archive_stories:[{id:'S-001',title:'Проверочная история',period:'1983',data:{story_state:'готовая история',story_text:'Настоящий текст рассказа',editorial_summary:'AI SUMMARY MUST NOT SHOW',quote:'AI QUOTE MUST NOT SHOW',people:['10A-11']}}]};
 function query(table){let filters=[],columns=null,single=false,limit=null,op='select';const q=new Proxy({}, {get(_,key){if(key==='then')return (resolve,reject)=>{window.auditCalls.push({table,op,columns,filters});setTimeout(()=>{let rows=(window.auditRows[table]||[]).map(x=>({...x}));for(const [k,v,t] of filters){if(t==='eq')rows=rows.filter(x=>x[k]===v);if(t==='in')rows=rows.filter(x=>v.includes(x[k]));}if(limit!==null)rows=rows.slice(0,limit);if(columns&&!columns.includes('*')&&!columns.includes(':'))rows=rows.map(x=>Object.fromEntries(columns.split(',').map(k=>[k,x[k]])));resolve({data:single?(rows[0]||null):rows,error:null});},window.auditDelay[table]||0)};return (...args)=>{if(key==='select')columns=args[0];if(['eq','in'].includes(key))filters.push([args[0],args[1],key]);if(['maybeSingle','single'].includes(key))single=true;if(key==='limit')limit=args[0];if(['insert','update','upsert','delete'].includes(key))op=key;return q}}});return q;}
 const listeners=[];window.auditSession=null;
 const sb={from:query,rpc:async(name,args)=>{auditCalls.push({rpc:name,args});return {data:0,error:null}},auth:{getSession:async()=>({data:{session:window.auditSession}}),onAuthStateChange(fn){listeners.push(fn);return {data:{subscription:{unsubscribe(){}}}}},signInWithOtp:async args=>{auditCalls.push({otp:args});return {error:window.auditAuthError}},verifyOtp:async()=>({data:{session:window.auditSession},error:window.auditVerifyError}),signOut:async()=>{window.auditSession=null;listeners.forEach(f=>f('SIGNED_OUT',null));return {error:null}}},storage:{from:()=>({createSignedUrl:async path=>({data:{signedUrl:window.auditImageUrl||location.origin+'/assets/home2/river-1960.jpg'},error:null}),createSignedUrls:async paths=>({data:paths.map(path=>({path,signedUrl:window.auditImageUrl||location.origin+'/assets/home2/river-1960.jpg'})),error:null}),remove:async()=>({error:null}),upload:async()=>({error:null})})},functions:{invoke:async()=>({data:{},error:null})},realtime:{setAuth(){}},channel:()=>({on(){return this},subscribe(){return this},unsubscribe(){}}),removeChannel:()=>{}};
 window.supabase={createClient:()=>sb};
};

module.exports=stub;
